In [137]:
import pandas as pd 
import numpy as np 
#시각화
import matplotlib.pyplot as plt
import seaborn as sns
#경고무시
import sys
import warnings

import warnings
warnings.filterwarnings('ignore')

In [138]:
def get_font_family():
    """
    시스템 환경에 따른 기본 폰트명을 반환하는 함수
    """
    import platform
    system_name = platform.system()
    # colab 사용자는 system_name이 'Linux'로 확인

    if system_name == "Darwin" :
        font_family = "AppleGothic"
    elif system_name == "Windows":
        font_family = "Malgun Gothic"
    else:
        # Linux
        # colab에서는 runtime을 <꼭> 재시작 해야함.
        # 런타임을 재시작 하지 않고 폰트 설치를 하면 기본 설정 폰트가 로드되어 한글이 깨짐.
        !apt-get update -qq
        !apt-get install fonts-nanum -qq  > /dev/null

        import matplotlib.font_manager as fm

        fontpath = '/usr/share/fonts/truetype/nanum/NanumBarunGothic.ttf'
        font = fm.FontProperties(fname=fontpath, size=9)
        fm._rebuild()
        font_family = "NanumBarunGothic"
    return font_family

In [139]:
# 시각화를 위한 폰트설정
# 위에서 만든 함수를 통해 시스템 폰트를 불러와서 font_family 라는 변수에 할당.
a = get_font_family()
# 폰트설정
import matplotlib.pyplot as plt 
plt.rc("font", family = a)
# 마이너스폰트 설정
plt.rc("axes", unicode_minus=False)
# ggplot으로 그래프 스타일 설정 / 개인 자유
plt.style.use("ggplot")

# 1. 서울시 기상데이터 살펴보기

In [141]:
weather_df = pd.read_csv('./서울시_기상데이터.csv', encoding='cp949')
weather_df

       지점                일시    기온  강수량   풍속  습도  일조시간  적설량  지면온도  지중온도
0     108   2020-01-01 1:00  -5.9  NaN  1.7  40   NaN  NaN  -2.4   3.2
1     108   2020-01-01 2:00  -5.7  NaN  0.1  42   NaN  NaN  -2.4   3.1
2     108   2020-01-01 3:00  -5.6  0.0  0.0  46   NaN  NaN  -2.7   3.1
3     108   2020-01-01 4:00  -5.4  NaN  0.0  50   NaN  NaN  -2.5   3.0
4     108   2020-01-01 5:00  -5.2  NaN  0.0  55   NaN  NaN  -2.2   3.0
...   ...               ...   ...  ...  ...  ..   ...  ...   ...   ...
8755  108  2020-12-30 20:00 -11.8  NaN  4.8  54   NaN  NaN  -6.5   2.2
8756  108  2020-12-30 21:00 -12.4  NaN  3.2  58   NaN  NaN  -6.9   2.2
8757  108  2020-12-30 22:00 -12.7  NaN  2.8  56   NaN  NaN  -7.1   2.1
8758  108  2020-12-30 23:00 -12.9  NaN  2.2  54   NaN  NaN  -7.3   2.1
8759  108   2020-12-31 0:00 -12.7  NaN  3.4  52   NaN  NaN  -7.6   2.1

[8760 rows x 10 columns]

In [142]:
# NaN 0으로 처리
weather_df = weather_df.fillna(0)
weather_df

       지점                일시    기온  강수량   풍속  습도  일조시간  적설량  지면온도  지중온도
0     108   2020-01-01 1:00  -5.9  0.0  1.7  40   0.0  0.0  -2.4   3.2
1     108   2020-01-01 2:00  -5.7  0.0  0.1  42   0.0  0.0  -2.4   3.1
2     108   2020-01-01 3:00  -5.6  0.0  0.0  46   0.0  0.0  -2.7   3.1
3     108   2020-01-01 4:00  -5.4  0.0  0.0  50   0.0  0.0  -2.5   3.0
4     108   2020-01-01 5:00  -5.2  0.0  0.0  55   0.0  0.0  -2.2   3.0
...   ...               ...   ...  ...  ...  ..   ...  ...   ...   ...
8755  108  2020-12-30 20:00 -11.8  0.0  4.8  54   0.0  0.0  -6.5   2.2
8756  108  2020-12-30 21:00 -12.4  0.0  3.2  58   0.0  0.0  -6.9   2.2
8757  108  2020-12-30 22:00 -12.7  0.0  2.8  56   0.0  0.0  -7.1   2.1
8758  108  2020-12-30 23:00 -12.9  0.0  2.2  54   0.0  0.0  -7.3   2.1
8759  108   2020-12-31 0:00 -12.7  0.0  3.4  52   0.0  0.0  -7.6   2.1

[8760 rows x 10 columns]

In [143]:
# 일시 컬럼을 일자와 시간으로 분리 
weather_df['일자'] = 0
for i in range(len(weather_df)):
    weather_df['일자'][i] = weather_df['일시'].iloc[i][:10]
weather_df

,지점,일시,기온,강수량,풍속,습도,일조시간,적설량,지면온도,지중온도,일자
0,108,2020-01-01 1:00,-5.9,0.0,1.7,40,0.0,0.0,-2.4,3.2,2020-01-01
1,108,2020-01-01 2:00,-5.7,0.0,0.1,42,0.0,0.0,-2.4,3.1,2020-01-01
2,108,2020-01-01 3:00,-5.6,0.0,0.0,46,0.0,0.0,-2.7,3.1,2020-01-01
3,108,2020-01-01 4:00,-5.4,0.0,0.0,50,0.0,0.0,-2.5,3.0,2020-01-01
4,108,2020-01-01 5:00,-5.2,0.0,0.0,55,0.0,0.0,-2.2,3.0,2020-01-01
...,...,...,...,...,...,...,...,...,...,...,...
8755,108,2020-12-30 20:00,-11.8,0.0,4.8,54,0.0,0.0,-6.5,2.2,2020-12-30
8756,108,2020-12-30 21:00,-12.4,0.0,3.2,58,0.0,0.0,-6.9,2.2,2020-12-30
8757,108,2020-12-30 22:00,-12.7,0.0,2.8,56,0.0,0.0,-7.1,2.1,2020-12-30
8758,108,2020-12-30 23:00,-12.9,0.0,2.2,54,0.0,0.0,-7.3,2.1,2020-12-30
8759,108,2020-12-31 0:00,-12.7,0.0,3.4,52,0.0,0.0,-7.6,2.1,2020-12-31

In [144]:
weather_df['시간'] = 0
for i in range(len(weather_df)):
    weather_df['시간'][i] = weather_df['일시'].iloc[i][11:]
weather_df

,지점,일시,기온,강수량,풍속,습도,일조시간,적설량,지면온도,지중온도,일자,시간
0,108,2020-01-01 1:00,-5.9,0.0,1.7,40,0.0,0.0,-2.4,3.2,2020-01-01,1:00
1,108,2020-01-01 2:00,-5.7,0.0,0.1,42,0.0,0.0,-2.4,3.1,2020-01-01,2:00
2,108,2020-01-01 3:00,-5.6,0.0,0.0,46,0.0,0.0,-2.7,3.1,2020-01-01,3:00
3,108,2020-01-01 4:00,-5.4,0.0,0.0,50,0.0,0.0,-2.5,3.0,2020-01-01,4:00
4,108,2020-01-01 5:00,-5.2,0.0,0.0,55,0.0,0.0,-2.2,3.0,2020-01-01,5:00
...,...,...,...,...,...,...,...,...,...,...,...,...
8755,108,2020-12-30 20:00,-11.8,0.0,4.8,54,0.0,0.0,-6.5,2.2,2020-12-30,20:00
8756,108,2020-12-30 21:00,-12.4,0.0,3.2,58,0.0,0.0,-6.9,2.2,2020-12-30,21:00
8757,108,2020-12-30 22:00,-12.7,0.0,2.8,56,0.0,0.0,-7.1,2.1,2020-12-30,22:00
8758,108,2020-12-30 23:00,-12.9,0.0,2.2,54,0.0,0.0,-7.3,2.1,2020-12-30,23:00
8759,108,2020-12-31 0:00,-12.7,0.0,3.4,52,0.0,0.0,-7.6,2.1,2020-12-31,0:00

In [145]:
# 필요한 컬럼만 남기고 정린
weather_df = weather_df[['일시','일자','시간', '기온','강수량','적설량']]
weather_df

                    일시          일자     시간    기온  강수량  적설량
0      2020-01-01 1:00  2020-01-01   1:00  -5.9  0.0  0.0
1      2020-01-01 2:00  2020-01-01   2:00  -5.7  0.0  0.0
2      2020-01-01 3:00  2020-01-01   3:00  -5.6  0.0  0.0
3      2020-01-01 4:00  2020-01-01   4:00  -5.4  0.0  0.0
4      2020-01-01 5:00  2020-01-01   5:00  -5.2  0.0  0.0
...                ...         ...    ...   ...  ...  ...
8755  2020-12-30 20:00  2020-12-30  20:00 -11.8  0.0  0.0
8756  2020-12-30 21:00  2020-12-30  21:00 -12.4  0.0  0.0
8757  2020-12-30 22:00  2020-12-30  22:00 -12.7  0.0  0.0
8758  2020-12-30 23:00  2020-12-30  23:00 -12.9  0.0  0.0
8759   2020-12-31 0:00  2020-12-31   0:00 -12.7  0.0  0.0

[8760 rows x 6 columns]

## 1-1. 강수 여부에 따른 구분
#### 눈/비가오면 사람들이 자차를 많이 이용할 것이다라는 가정하에 교통량이 많은 시간보다 1시간 앞서 비가오는지 확인

- 서울시 교통량 조사에 따르면 주중에는 오전 7시-9시, 오후 6시~7시에 교통량이 많음
- 주말에는 13시-14시, 16~17시 사이 교통량이 많음
- 이 시간대를 기준으로 정리

### 주말에 눈/비가오면?

In [146]:
import datetime as dt

# datetime 형식으로 자료형 바꿔주기
weather_df['일자'] = pd.to_datetime(weather_df['일자'])

# 요일 컬럼 넣어주기 (월요일:0 ~ 일요일:6)
# 주말(토,일)은 5,6
weather_df['요일'] = weather_df['일자'].dt.weekday
weather_df

                    일시         일자     시간    기온  강수량  적설량  요일
0      2020-01-01 1:00 2020-01-01   1:00  -5.9  0.0  0.0   2
1      2020-01-01 2:00 2020-01-01   2:00  -5.7  0.0  0.0   2
2      2020-01-01 3:00 2020-01-01   3:00  -5.6  0.0  0.0   2
3      2020-01-01 4:00 2020-01-01   4:00  -5.4  0.0  0.0   2
4      2020-01-01 5:00 2020-01-01   5:00  -5.2  0.0  0.0   2
...                ...        ...    ...   ...  ...  ...  ..
8755  2020-12-30 20:00 2020-12-30  20:00 -11.8  0.0  0.0   2
8756  2020-12-30 21:00 2020-12-30  21:00 -12.4  0.0  0.0   2
8757  2020-12-30 22:00 2020-12-30  22:00 -12.7  0.0  0.0   2
8758  2020-12-30 23:00 2020-12-30  23:00 -12.9  0.0  0.0   2
8759   2020-12-31 0:00 2020-12-31   0:00 -12.7  0.0  0.0   3

[8760 rows x 7 columns]

## 1) 평일 눈/비가오는지 여부에 따른 파생변수 만들기

In [147]:
# 평일
weekday = weather_df[(weather_df['요일'] != 5) & (weather_df['요일'] != 6)]
weekday

                    일시         일자     시간    기온  강수량  적설량  요일
0      2020-01-01 1:00 2020-01-01   1:00  -5.9  0.0  0.0   2
1      2020-01-01 2:00 2020-01-01   2:00  -5.7  0.0  0.0   2
2      2020-01-01 3:00 2020-01-01   3:00  -5.6  0.0  0.0   2
3      2020-01-01 4:00 2020-01-01   4:00  -5.4  0.0  0.0   2
4      2020-01-01 5:00 2020-01-01   5:00  -5.2  0.0  0.0   2
...                ...        ...    ...   ...  ...  ...  ..
8755  2020-12-30 20:00 2020-12-30  20:00 -11.8  0.0  0.0   2
8756  2020-12-30 21:00 2020-12-30  21:00 -12.4  0.0  0.0   2
8757  2020-12-30 22:00 2020-12-30  22:00 -12.7  0.0  0.0   2
8758  2020-12-30 23:00 2020-12-30  23:00 -12.9  0.0  0.0   2
8759   2020-12-31 0:00 2020-12-31   0:00 -12.7  0.0  0.0   3

[6264 rows x 7 columns]

In [148]:
# 주중에는 오전 7시, 오후 5시로 선택

# weekday = weekday[(weekday['시간']=='7:00') | (weekday['시간']=='17:00')]
# weekday

In [149]:
# 주중에는 오전 7시로 선택 
weekday = weekday[(weekday['시간']=='7:00')]
weekday

                   일시         일자    시간    기온  강수량  적설량  요일
6     2020-01-01 7:00 2020-01-01  7:00  -4.6  0.0  0.0   2
30    2020-01-02 7:00 2020-01-02  7:00  -0.5  0.0  0.0   3
54    2020-01-03 7:00 2020-01-03  7:00  -3.0  0.0  0.0   4
126   2020-01-06 7:00 2020-01-06  7:00   2.1  0.0  0.0   0
150   2020-01-07 7:00 2020-01-07  7:00   5.6  0.0  0.0   1
...               ...        ...   ...   ...  ...  ...  ..
8598  2020-12-24 7:00 2020-12-24  7:00   3.2  0.0  0.0   3
8622  2020-12-25 7:00 2020-12-25  7:00  -3.8  0.0  0.0   4
8694  2020-12-28 7:00 2020-12-28  7:00   5.3  0.0  0.0   0
8718  2020-12-29 7:00 2020-12-29  7:00   1.9  0.0  0.0   1
8742  2020-12-30 7:00 2020-12-30  7:00 -11.8  0.0  0.0   2

[261 rows x 7 columns]

In [150]:
weekday.iloc[0]['강수량']

0.0

In [151]:
weekday['강수여부'] = 0

for i in range(len(weekday)):
    if weekday.iloc[i]['강수량'] != 0.0:
        weekday.iloc[i]['강수여부'] = 1
    if weekday.iloc[i]['적설량'] != 0.0:
        weekday.iloc[i]['강수여부'] = 1
weekday

                   일시         일자    시간    기온  강수량  적설량  요일  강수여부
6     2020-01-01 7:00 2020-01-01  7:00  -4.6  0.0  0.0   2     0
30    2020-01-02 7:00 2020-01-02  7:00  -0.5  0.0  0.0   3     0
54    2020-01-03 7:00 2020-01-03  7:00  -3.0  0.0  0.0   4     0
126   2020-01-06 7:00 2020-01-06  7:00   2.1  0.0  0.0   0     0
150   2020-01-07 7:00 2020-01-07  7:00   5.6  0.0  0.0   1     0
...               ...        ...   ...   ...  ...  ...  ..   ...
8598  2020-12-24 7:00 2020-12-24  7:00   3.2  0.0  0.0   3     0
8622  2020-12-25 7:00 2020-12-25  7:00  -3.8  0.0  0.0   4     0
8694  2020-12-28 7:00 2020-12-28  7:00   5.3  0.0  0.0   0     0
8718  2020-12-29 7:00 2020-12-29  7:00   1.9  0.0  0.0   1     0
8742  2020-12-30 7:00 2020-12-30  7:00 -11.8  0.0  0.0   2     0

[261 rows x 8 columns]

## 2) 주말 눈/비가오는지 여부에 따른 파생변수 만들기

In [152]:
# 주말
weekend = weather_df[(weather_df['요일'] == 5) | (weather_df['요일'] == 6)]
weekend

                    일시         일자     시간   기온  강수량  적설량  요일
71     2020-01-04 0:00 2020-01-04   0:00 -1.5  0.0  0.0   5
72     2020-01-04 1:00 2020-01-04   1:00 -1.6  0.0  0.0   5
73     2020-01-04 2:00 2020-01-04   2:00 -1.9  0.0  0.0   5
74     2020-01-04 3:00 2020-01-04   3:00 -2.1  0.0  0.0   5
75     2020-01-04 4:00 2020-01-04   4:00 -2.3  0.0  0.0   5
...                ...        ...    ...  ...  ...  ...  ..
8682  2020-12-27 19:00 2020-12-27  19:00  7.2  0.0  0.0   6
8683  2020-12-27 20:00 2020-12-27  20:00  6.5  0.0  0.0   6
8684  2020-12-27 21:00 2020-12-27  21:00  7.1  0.0  0.0   6
8685  2020-12-27 22:00 2020-12-27  22:00  6.7  0.0  0.0   6
8686  2020-12-27 23:00 2020-12-27  23:00  6.4  0.0  0.0   6

[2496 rows x 7 columns]

In [153]:
# 주말에는 12시 기준으로 선택

weekend = weekend[(weekend['시간']=='12:00')]
weekend

                    일시         일자     시간   기온  강수량  적설량  요일
83    2020-01-04 12:00 2020-01-04  12:00  4.2  0.0  0.0   5
107   2020-01-05 12:00 2020-01-05  12:00  4.0  0.0  0.0   6
251   2020-01-11 12:00 2020-01-11  12:00  2.6  0.0  0.0   5
275   2020-01-12 12:00 2020-01-12  12:00  0.4  0.0  0.0   6
419   2020-01-18 12:00 2020-01-18  12:00  2.3  0.0  0.0   5
...                ...        ...    ...  ...  ...  ...  ..
8339  2020-12-13 12:00 2020-12-13  12:00  0.8  0.6  2.6   6
8483  2020-12-19 12:00 2020-12-19  12:00 -3.4  0.0  0.0   5
8507  2020-12-20 12:00 2020-12-20  12:00 -0.5  0.0  0.0   6
8651  2020-12-26 12:00 2020-12-26  12:00  5.9  0.0  0.0   5
8675  2020-12-27 12:00 2020-12-27  12:00  8.1  0.0  0.0   6

[104 rows x 7 columns]

In [154]:
weekend['강수여부'] = 0

for i in range(len(weekend)):
    if weekend.iloc[i]['강수량'] != 0.0:
        weekend.iloc[i]['강수여부'] = 1
    if weekend.iloc[i]['적설량'] != 0.0:
        weekend.iloc[i]['강수여부'] = 1
weekend

                    일시         일자     시간   기온  강수량  적설량  요일  강수여부
83    2020-01-04 12:00 2020-01-04  12:00  4.2  0.0  0.0   5     0
107   2020-01-05 12:00 2020-01-05  12:00  4.0  0.0  0.0   6     0
251   2020-01-11 12:00 2020-01-11  12:00  2.6  0.0  0.0   5     0
275   2020-01-12 12:00 2020-01-12  12:00  0.4  0.0  0.0   6     0
419   2020-01-18 12:00 2020-01-18  12:00  2.3  0.0  0.0   5     0
...                ...        ...    ...  ...  ...  ...  ..   ...
8339  2020-12-13 12:00 2020-12-13  12:00  0.8  0.6  2.6   6     0
8483  2020-12-19 12:00 2020-12-19  12:00 -3.4  0.0  0.0   5     0
8507  2020-12-20 12:00 2020-12-20  12:00 -0.5  0.0  0.0   6     0
8651  2020-12-26 12:00 2020-12-26  12:00  5.9  0.0  0.0   5     0
8675  2020-12-27 12:00 2020-12-27  12:00  8.1  0.0  0.0   6     0

[104 rows x 8 columns]

In [155]:
# 주중 주말 합쳐서 하나의 데이터프레임 만들기
everyday = pd.concat([weekday, weekend], ignore_index=True )
everyday.sort_values(by=['일자'], axis=0, inplace=True, ignore_index=True)
everyday

                   일시         일자     시간    기온  강수량  적설량  요일  강수여부
0     2020-01-01 7:00 2020-01-01   7:00  -4.6  0.0  0.0   2     0
1     2020-01-02 7:00 2020-01-02   7:00  -0.5  0.0  0.0   3     0
2     2020-01-03 7:00 2020-01-03   7:00  -3.0  0.0  0.0   4     0
3    2020-01-04 12:00 2020-01-04  12:00   4.2  0.0  0.0   5     0
4    2020-01-05 12:00 2020-01-05  12:00   4.0  0.0  0.0   6     0
..                ...        ...    ...   ...  ...  ...  ..   ...
360  2020-12-26 12:00 2020-12-26  12:00   5.9  0.0  0.0   5     0
361  2020-12-27 12:00 2020-12-27  12:00   8.1  0.0  0.0   6     0
362   2020-12-28 7:00 2020-12-28   7:00   5.3  0.0  0.0   0     0
363   2020-12-29 7:00 2020-12-29   7:00   1.9  0.0  0.0   1     0
364   2020-12-30 7:00 2020-12-30   7:00 -11.8  0.0  0.0   2     0

[365 rows x 8 columns]

In [156]:
raining_day = everyday[['일자', '강수여부']]
raining_day

            일자  강수여부
0   2020-01-01     0
1   2020-01-02     0
2   2020-01-03     0
3   2020-01-04     0
4   2020-01-05     0
..         ...   ...
360 2020-12-26     0
361 2020-12-27     0
362 2020-12-28     0
363 2020-12-29     0
364 2020-12-30     0

[365 rows x 2 columns]

## 1-2. 기온에 따른 분류

- 폭염과 한파로 나눠보자

○ 폭염주의보 : 최고기온 33℃ 이상이고 일최고열지수(Heat Index) 32℃ 이상인 상태가 2일 이상지속될 것으로 예상되는 경우 발령

○ 한파주의보는 아침 최저기온이 영하 12도 이하로 2일 이상 지속될 것이 예상될 때

*참고] 상대 온도는 고려하지 않음(한파주의보는 10월부터 이듬해 4월까지 아침 최저기온이 전날보다 10도 이상 떨어질 것으로 예상될 때 발령)

In [157]:
temperatures = weather_df[(weather_df['기온'] > 33) | (weather_df['기온'] < -12)]
day = list(temperatures['일자'].unique())
day

[numpy.datetime64('2020-06-13T00:00:00.000000000'),
 numpy.datetime64('2020-06-22T00:00:00.000000000'),
 numpy.datetime64('2020-08-25T00:00:00.000000000'),
 numpy.datetime64('2020-08-26T00:00:00.000000000'),
 numpy.datetime64('2020-12-30T00:00:00.000000000'),
 numpy.datetime64('2020-12-31T00:00:00.000000000')]

In [158]:
everyday['이상기온'] =0 # 이상 기온 여부 변수 생성
for i in range(len(everyday)):
    if everyday['일자'].iloc[i] in day:
        everyday['이상기온'].iloc[i] = 1
everyday

                   일시         일자     시간    기온  강수량  적설량  요일  강수여부  이상기온
0     2020-01-01 7:00 2020-01-01   7:00  -4.6  0.0  0.0   2     0     0
1     2020-01-02 7:00 2020-01-02   7:00  -0.5  0.0  0.0   3     0     0
2     2020-01-03 7:00 2020-01-03   7:00  -3.0  0.0  0.0   4     0     0
3    2020-01-04 12:00 2020-01-04  12:00   4.2  0.0  0.0   5     0     0
4    2020-01-05 12:00 2020-01-05  12:00   4.0  0.0  0.0   6     0     0
..                ...        ...    ...   ...  ...  ...  ..   ...   ...
360  2020-12-26 12:00 2020-12-26  12:00   5.9  0.0  0.0   5     0     0
361  2020-12-27 12:00 2020-12-27  12:00   8.1  0.0  0.0   6     0     0
362   2020-12-28 7:00 2020-12-28   7:00   5.3  0.0  0.0   0     0     0
363   2020-12-29 7:00 2020-12-29   7:00   1.9  0.0  0.0   1     0     0
364   2020-12-30 7:00 2020-12-30   7:00 -11.8  0.0  0.0   2     0     1

[365 rows x 9 columns]

In [159]:
weather_var = everyday[['일자', '강수여부','이상기온']]
weather_var

            일자  강수여부  이상기온
0   2020-01-01     0     0
1   2020-01-02     0     0
2   2020-01-03     0     0
3   2020-01-04     0     0
4   2020-01-05     0     0
..         ...   ...   ...
360 2020-12-26     0     0
361 2020-12-27     0     0
362 2020-12-28     0     0
363 2020-12-29     0     0
364 2020-12-30     0     1

[365 rows x 3 columns]

# 2. 교통데이터 살펴보기

In [8]:
traffic_df = pd.read_excel('./2020교통량통합.xlsx', engine='openpyxl')
traffic_df

,DATE,지점명,지점번호,방향,구분,0시,1시,2시,3시,4시,...,14시,15시,16시,17시,18시,19시,20시,21시,22시,23시
0,2020-01-01,성산로(금화터널),A-01,유입,봉원고가차도->독립문역,712.0,645.0,437.0,309.0,290.0,...,1472.0,1416.0,1483.0,1329.0,1157.0,1014.0,954.0,849.0,780.0,480.0
1,2020-01-02,성산로(금화터널),A-01,유입,봉원고가차도->독립문역,315.0,222.0,186.0,165.0,266.0,...,1792.0,1897.0,1842.0,2061.0,1994.0,1443.0,1233.0,1165.0,1094.0,852.0
2,2020-01-03,성산로(금화터널),A-01,유입,봉원고가차도->독립문역,632.0,457.0,295.0,236.0,279.0,...,2004.0,1929.0,2049.0,2140.0,2178.0,1654.0,1356.0,1260.0,1253.0,941.0
3,2020-01-04,성산로(금화터널),A-01,유입,봉원고가차도->독립문역,740.0,518.0,388.0,331.0,330.0,...,1837.0,1788.0,1588.0,1669.0,1530.0,1222.0,1143.0,1089.0,1039.0,791.0
4,2020-01-05,성산로(금화터널),A-01,유입,봉원고가차도->독립문역,533.0,424.0,297.0,230.0,209.0,...,1634.0,1673.0,1494.0,1429.0,1288.0,1035.0,987.0,884.0,803.0,564.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98815,2020-12-27,서부간선도로,F-09,유출,목동교->신정교,1310.0,804.0,582.0,473.0,488.0,...,3026.0,2957.0,2799.0,2858.0,2805.0,3031.0,3173.0,2928.0,2278.0,1559.0
98816,2020-12-28,서부간선도로,F-09,유출,목동교->신정교,1030.0,614.0,501.0,565.0,1160.0,...,2925.0,2595.0,2705.0,2264.0,2272.0,2954.0,3081.0,3099.0,2521.0,1837.0
98817,2020-12-29,서부간선도로,F-09,유출,목동교->신정교,1294.0,833.0,582.0,597.0,900.0,...,2634.0,2851.0,2704.0,2163.0,2165.0,2738.0,3054.0,3078.0,2544.0,1952.0
98818,2020-12-30,서부간선도로,F-09,유출,목동교->신정교,1451.0,929.0,616.0,591.0,929.0,...,2901.0,2636.0,2175.0,2036.0,1969.0,2787.0,3058.0,2936.0,2730.0,2160.0
98819,2020-12-31,서부간선도로,F-09,유출,목동교->신정교,1497.0,926.0,721.0,540.0,857.0,...,2742.0,2261.0,2021.0,2043.0,1782.0,2543.0,2927.0,2627.0,2699.0,1955.0

## 교통 이동량을 
- 특정 구역의 특정 시간대 교통량의 많고 적음으로 분류?
- 그렇게되면.. 교통량이 많은 지역은 주차장앱을 사용할 수 있지만, 다른 지역은 아닐텐데..
- 서울 전체 지역에 대한 교통량? 특정 일자로 봐야할까?
- 간선도로와 도심을 기준?

#### 서울 전체(유입은 많고 유출이 적어서 서울 내에 차가 많은 날을 꼽아볼까?)
- 2020 요일별 교통량 추이를 보면 금요일이 가장 높음
- 주말보단 주중에 유입/유출 차량이 많음

더 논의해 봅시다.

In [9]:
traffic_df.groupby(['DATE']).count()

,지점명,지점번호,방향,구분,0시,1시,2시,3시,4시,5시,...,14시,15시,16시,17시,18시,19시,20시,21시,22시,23시
DATE,,,,,,,,,,,,,,,,,,,,,
2020-01-01,270,270,270,270,258,258,258,258,258,258,...,257,257,257,257,258,258,258,258,258,258
2020-01-02,270,270,270,270,257,257,257,257,257,257,...,255,258,258,258,258,258,258,258,258,258
2020-01-03,270,270,270,270,259,259,259,259,259,259,...,259,259,259,259,259,259,259,259,259,259
2020-01-04,270,270,270,270,260,260,260,260,260,260,...,257,257,259,260,260,260,260,260,260,260
2020-01-05,270,270,270,270,260,260,260,260,260,260,...,260,260,260,260,260,260,260,260,260,260
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-12-27,270,270,270,270,232,232,232,232,232,232,...,236,236,236,236,236,236,235,235,235,235
2020-12-28,270,270,270,270,236,236,236,236,236,236,...,235,235,235,235,235,235,235,235,235,235
2020-12-29,270,270,270,270,235,235,235,235,235,235,...,238,238,238,238,238,238,238,239,238,238
2020-12-30,270,270,270,270,238,238,238,236,236,235,...,236,236,236,236,236,236,236,236,236,236
2020-12-31,270,270,270,270,236,236,236,236,236,236,...,235,235,235,235,235,235,235,235,235,235