In [37]:
import pandas as pd
test1 = pd.read_csv('./2_표제부.csv', encoding='cp949', engine='python')

In [3]:
test1.head()

,순번,법정동코드,대지구분코드,번,지,대장구분코드명,건물명,동명칭,연면적,구조코드명,주용도코드명,세대수(세대),사용승인연도,일
0,24,10100,3,0,0,집합,왕관빌딩,왕관빌딩,18426.0794,철근콘크리트구조,제1종근린생활시설,0,2019.0,1231.0
1,2345,10900,3,0,0,일반,다정동 2111-2105 단독주택 (이동우),주건축물제1동,199.5,철근콘크리트구조,단독주택,1,2019.0,1231.0
2,9660,25032,1,445,6,일반,NaN,주건축물제1동,436.84,철근콘크리트구조,단독주택,0,2019.0,1231.0
3,22633,35022,1,280,4,일반,NaN,주건축물제1동,198,일반철골구조,창고시설,0,2019.0,1231.0
4,22634,35022,1,280,4,일반,NaN,주건축물제2동,198,일반철골구조,창고시설,0,2019.0,1231.0

In [4]:
#지역별 유니크 분포 확인
test1['법정동코드'].unique()

array([10100, 10900, 25032, 35022, 35024, 36026, 36033, 37035, 10600,
       11400, 25021, 25028, 36024, 36031, 37027, 37028, 37032, 32024,
       39023, 32027, 34045, 34021, 34040, 25023, 37034, 38025, 32021,
       35026, 32022, 35033, 25027, 33021, 36029, 37023, 34041, 35025,
       25029, 32030, 33024, 35029, 25034, 36023, 31023, 34026, 34029,
       38026, 38030, 35021, 34023, 35027, 11200, 33022, 37026, 35023,
       25026, 25030, 37021, 25024, 36030, 34044, 38029, 36021, 25022,
       39024, 35031, 34022, 34034, 38023, 38031, 39022, 34025, 36022,
       37022, 39021, 37033, 36028, 34024, 10700, 31021, 34039, 38022,
       37029, 33025, 34028, 34033, 36025, 36027, 38021, 31022, 32026,
       35028, 25031, 33028, 25025, 11100, 11300, 10300, 32023, 38024,
       38027, 37030, 11000, 33027, 34027, 34030, 37031, 25033, 32025,
       34031, 38028, 33026, 36032, 31024, 34043, 34036, 33023, 37024,
       34032, 35032, 34038, 35034, 10200, 37025, 34046, 34042, 10500,
       31025, 11800, 34035, 34037, 11700, 32028, 10400, 31027, 35030,
       31026, 10800, 11600, 11500, 32029], dtype=int64)

In [3]:
test1['법정동코드'].nunique()

140

In [5]:
test1.dtypes

순번           int64
법정동코드        int64
대지구분코드       int64
번            int64
지            int64
대장구분코드명     object
건물명         object
동명칭         object
연면적         object
구조코드명       object
주용도코드명      object
세대수(세대)     object
사용승인연도     float64
일          float64
dtype: object

In [4]:
#데이터마다 연도 표기 형식이 다름 
#연월 분리 위해 형변환
test1['사용승인연도'] = test1['사용승인연도'].fillna(0)
test1['사용승인연도']= test1['사용승인연도'].astype(int)
test1.head()

,순번,법정동코드,대지구분코드,번,지,대장구분코드명,건물명,동명칭,연면적,구조코드명,주용도코드명,세대수(세대),사용승인연도,일
0,24,10100,3,0,0,집합,왕관빌딩,왕관빌딩,18426.0794,철근콘크리트구조,제1종근린생활시설,0,2019,1231.0
1,2345,10900,3,0,0,일반,다정동 2111-2105 단독주택 (이동우),주건축물제1동,199.5,철근콘크리트구조,단독주택,1,2019,1231.0
2,9660,25032,1,445,6,일반,NaN,주건축물제1동,436.84,철근콘크리트구조,단독주택,0,2019,1231.0
3,22633,35022,1,280,4,일반,NaN,주건축물제1동,198,일반철골구조,창고시설,0,2019,1231.0
4,22634,35022,1,280,4,일반,NaN,주건축물제2동,198,일반철골구조,창고시설,0,2019,1231.0

In [6]:
test2_1 = test1.groupby('사용승인연도')['주용도코드명'].count().reset_index()

In [7]:
test2_1.head()

   사용승인연도  주용도코드명
0       0    1209
1    1810       2
2    1818       1
3    1820       4
4    1827       1

In [30]:
#test2_1.to_csv('./표제부_연도별_부동산.csv')

In [21]:
#연도별 기준으로 본 시설 승인 갯수
# 표기가 안된 것도 있고 --> 0으로 
# 1810년에 지어져 지금 상황이 어떤지 확인 필요

test1_2 = test1.groupby(['사용승인연도' , '주용도코드명'])['순번'].count().reset_index()
test1_2

      사용승인연도      주용도코드명   순번
0          0        공동주택   17
1          0          공장   87
2          0   교육연구및복지시설    4
3          0      교육연구시설   57
4          0     교정및군사시설   18
5          0      근린생활시설    1
6          0       노유자시설    3
7          0        단독주택  714
8          0    동.식물관련시설   98
9          0     문화및집회시설    1
10         0  분뇨.쓰레기처리시설    2
11         0        수련시설    2
12         0        숙박시설    2
13         0        운동시설    1
14         0        운수시설    5
15         0  위험물저장및처리시설    6
16         0        의료시설    1
17         0     자동차관련시설    1
18         0   제1종근린생활시설   74
19         0   제2종근린생활시설   38
20         0        종교시설    4
21         0        창고시설   72
22         0    철근콘크리트구조    1
23      1810        단독주택    2
24      1818        단독주택    1
25      1820        단독주택    3
26      1820   제2종근린생활시설    1
27      1827        단독주택    1
28      1850        단독주택    3
29      1860        단독주택    2
...      ...         ...  ...
1082    2019  위험물저장및처리시설   14
1083    2019        의료시설    1
1084    2019     자동차관련시설    6
1085    2019    자원순환관련시설    6
1086    2019   제1종근린생활시설  102
1087    2019   제2종근린생활시설  195
1088    2019        종교시설    3
1089    2019        창고시설   36
1090    2019        판매시설    4
1091    2020        공동주택  186
1092    2020          공장   35
1093    2020      관광휴게시설    7
1094    2020      교육연구시설   16
1095    2020     교정및군사시설    2
1096    2020       노유자시설    3
1097    2020        단독주택  282
1098    2020    동.식물관련시설   46
1099    2020     문화및집회시설   19
1100    2020        발전시설    1
1101    2020        수련시설    1
1102    2020        업무시설   13
1103    2020        운동시설    2
1104    2020  위험물저장및처리시설   14
1105    2020        의료시설    1
1106    2020     자동차관련시설    8
1107    2020    자원순환관련시설    6
1108    2020   제1종근린생활시설   84
1109    2020   제2종근린생활시설  106
1110    2020        창고시설   32
1111    2020        판매시설    2

[1112 rows x 3 columns]

In [11]:
test1.head()

,순번,법정동코드,대지구분코드,번,지,대장구분코드명,건물명,동명칭,연면적,구조코드명,주용도코드명,세대수(세대),사용승인연도,일
0,24,10100,3,0,0,집합,왕관빌딩,왕관빌딩,18426.0794,철근콘크리트구조,제1종근린생활시설,0,2019,1231.0
1,2345,10900,3,0,0,일반,다정동 2111-2105 단독주택 (이동우),주건축물제1동,199.5,철근콘크리트구조,단독주택,1,2019,1231.0
2,9660,25032,1,445,6,일반,NaN,주건축물제1동,436.84,철근콘크리트구조,단독주택,0,2019,1231.0
3,22633,35022,1,280,4,일반,NaN,주건축물제1동,198,일반철골구조,창고시설,0,2019,1231.0
4,22634,35022,1,280,4,일반,NaN,주건축물제2동,198,일반철골구조,창고시설,0,2019,1231.0

In [13]:
#번지를 기준으로 어떻게 변화했는지 확인 작업
test3 = test1

In [18]:
test3['번']= test3['번'].astype(str)

In [19]:
test3['지']= test3['지'].astype(str)

In [20]:
test3['번지'] = test3[['번', '지']].apply(lambda x: '_'.join(x), axis=1)

In [21]:
test3.head()

,순번,법정동코드,대지구분코드,번,지,대장구분코드명,건물명,동명칭,연면적,구조코드명,주용도코드명,세대수(세대),사용승인연도,일,번지
0,24,10100,3,0,0,집합,왕관빌딩,왕관빌딩,18426.0794,철근콘크리트구조,제1종근린생활시설,0,2019,1231.0,0_0
1,2345,10900,3,0,0,일반,다정동 2111-2105 단독주택 (이동우),주건축물제1동,199.5,철근콘크리트구조,단독주택,1,2019,1231.0,0_0
2,9660,25032,1,445,6,일반,NaN,주건축물제1동,436.84,철근콘크리트구조,단독주택,0,2019,1231.0,445_6
3,22633,35022,1,280,4,일반,NaN,주건축물제1동,198,일반철골구조,창고시설,0,2019,1231.0,280_4
4,22634,35022,1,280,4,일반,NaN,주건축물제2동,198,일반철골구조,창고시설,0,2019,1231.0,280_4

In [22]:
del test3['번']

In [23]:
del test3['지']

In [24]:
test3.head()

,순번,법정동코드,대지구분코드,대장구분코드명,건물명,동명칭,연면적,구조코드명,주용도코드명,세대수(세대),사용승인연도,일,번지
0,24,10100,3,집합,왕관빌딩,왕관빌딩,18426.0794,철근콘크리트구조,제1종근린생활시설,0,2019,1231.0,0_0
1,2345,10900,3,일반,다정동 2111-2105 단독주택 (이동우),주건축물제1동,199.5,철근콘크리트구조,단독주택,1,2019,1231.0,0_0
2,9660,25032,1,일반,NaN,주건축물제1동,436.84,철근콘크리트구조,단독주택,0,2019,1231.0,445_6
3,22633,35022,1,일반,NaN,주건축물제1동,198,일반철골구조,창고시설,0,2019,1231.0,280_4
4,22634,35022,1,일반,NaN,주건축물제2동,198,일반철골구조,창고시설,0,2019,1231.0,280_4

In [26]:
#번지와 건물명으로 연도별 변화 분석하려 했음 
test1= test3.groupby(['번지', '건물명', '주용도코드명'])['사용승인연도'].max().reset_index()

In [27]:
#결과 번지가 정확하지 않음 
# 표기 문제 0번 0지로 표기 되어 있는 아이들 존재  
test1.head()

    번지                    건물명 주용도코드명  사용승인연도
0  0_0              (주)엠케이케미칼     공장    2004
1  0_0  1-1생활권 D9-105 저에너지하우스   단독주택    2015
2  0_0      1-2생활권 D1-26 단독주택   단독주택    2014
3  0_0         1-2생활권 D1-50블록   단독주택    2015
4  0_0    1-2생활권 D1-52블록 단독주택   단독주택    2014

In [35]:
test1.to_csv('./2/test1.csv', encoding="cp949")

In [29]:
test2= test1.groupby(['사용승인연도','주용도코드명'])['건물명'].count().reset_index()

In [30]:
test2

     사용승인연도      주용도코드명  건물명
0         0        공동주택    6
1         0          공장    6
2         0   교육연구및복지시설    3
3         0      교육연구시설   18
4         0     교정및군사시설   13
5         0      근린생활시설    1
6         0        단독주택    7
7         0    동.식물관련시설    2
8         0  위험물저장및처리시설    1
9         0   제1종근린생활시설    4
10        0   제2종근린생활시설    3
11        0        창고시설    3
12        0    철근콘크리트구조    1
13     1908        단독주택    1
14     1910        단독주택    1
15     1915        단독주택    2
16     1920        단독주택    2
17     1923        단독주택    1
18     1925        단독주택    3
19     1925   제2종근린생활시설    1
20     1926        단독주택    1
21     1930        단독주택    5
22     1935   제2종근린생활시설    1
23     1936        단독주택    1
24     1938        단독주택    1
25     1940        단독주택    2
26     1940   제1종근린생활시설    1
27     1942        단독주택    1
28     1944        단독주택    2
29     1945        단독주택    2
..      ...         ...  ...
507    2019        운동시설    2
508    2019  위험물저장및처리시설    5
509    2019        의료시설    1
510    2019     자동차관련시설    1
511    2019    자원순환관련시설    1
512    2019   제1종근린생활시설   27
513    2019   제2종근린생활시설   38
514    2019        종교시설    3
515    2019        창고시설    3
516    2019        판매시설    2
517    2020        공동주택   10
518    2020          공장    4
519    2020      교육연구시설    7
520    2020     교정및군사시설    2
521    2020       노유자시설    3
522    2020        단독주택   40
523    2020    동.식물관련시설    4
524    2020     문화및집회시설    3
525    2020        발전시설    1
526    2020        수련시설    1
527    2020        업무시설    9
528    2020        운동시설    2
529    2020  위험물저장및처리시설    4
530    2020        의료시설    1
531    2020     자동차관련시설    3
532    2020    자원순환관련시설    2
533    2020   제1종근린생활시설   15
534    2020   제2종근린생활시설   17
535    2020        창고시설    2
536    2020        판매시설    1

[537 rows x 3 columns]

In [33]:
test2.to_csv('./2/test4.csv', encoding="cp949")

In [39]:
test1['사용승인연도'] = test1['사용승인연도'].fillna(0)
test1['사용승인연도']= test1['사용승인연도'].astype(int)
test1.head()

,순번,법정동코드,대지구분코드,번,지,대장구분코드명,건물명,동명칭,연면적,구조코드명,주용도코드명,세대수(세대),사용승인연도,일
0,24,10100,3,0,0,집합,왕관빌딩,왕관빌딩,18426.0794,철근콘크리트구조,제1종근린생활시설,0,2019,1231.0
1,2345,10900,3,0,0,일반,다정동 2111-2105 단독주택 (이동우),주건축물제1동,199.5,철근콘크리트구조,단독주택,1,2019,1231.0
2,9660,25032,1,445,6,일반,NaN,주건축물제1동,436.84,철근콘크리트구조,단독주택,0,2019,1231.0
3,22633,35022,1,280,4,일반,NaN,주건축물제1동,198,일반철골구조,창고시설,0,2019,1231.0
4,22634,35022,1,280,4,일반,NaN,주건축물제2동,198,일반철골구조,창고시설,0,2019,1231.0

In [40]:
# 부정확한 데이터 제외위해서 
# 2000년이후  데이터만 뽑음
# 2000년 기준 사유 --> 세종시 출범 2012년을 기준으로 전후 +-8년을 하면 어떤 변화가 있는지 확인할 수 있을거라 판단
test1_1=test1[test1['사용승인연도']>=2000]

In [44]:
test1_1.tail()

,순번,법정동코드,대지구분코드,번,지,대장구분코드명,건물명,동명칭,연면적,구조코드명,주용도코드명,세대수(세대),사용승인연도,일
27917,34719,38029,1,345,7,일반,NaN,NaN,121.05,벽돌구조,단독주택,0,2003,NaN
27918,28203,36031,1,1171,2,일반,NaN,2동,120.94,강파이프구조,동.식물관련시설,0,2001,NaN
27919,28204,36031,1,1171,2,일반,NaN,3동,68,블록구조,창고시설,0,2001,NaN
27920,28206,36031,1,1171,2,일반,NaN,4동,124.5,강파이프구조,동.식물관련시설,0,2001,NaN
27921,35263,38031,1,277,0,일반,NaN,C동,156.36,강파이프구조,단독주택,0,2000,NaN

In [45]:
#데이터 저장후 태블로
test1_1.to_csv('./2/test1_1.csv', encoding="cp949")